### ISSUE TITLE
test: fix the DNS timeout test

### ISSUE THREAD

**Issue by sarahdayan** [algolia/algoliasearch-client-csharp#627] opened 2019-07-10 23:27 UTC
The spec for this new test is described here: https://github.com/algolia/algoliasearch-client-specs/pull/34

**Comment by spinach** [comment] 2020-08-18 09:05
Closing as this seems a duplicate of https://github.com/algolia/algoliasearch-client-csharp/issues/586

**Closed by spinach** 2020-08-18 09:05 UTC
