### ISSUE TITLE
Secured API keys not working

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-client-csharp#124] opened 2016-10-10 20:24 UTC
When I use this code in code behind

```
algoliaSettings.PublicKey = client.GenerateSecuredApiKey(algoliaSettings.SearchApiKey, newQuery().EnableAnalytics(true));
```

it will work.

But when I use this it will not

```
algoliaSettings.PublicKey = client.GenerateSecuredApiKey(algoliaSettings.SearchApiKey, newQuery().SetFilters("filter:myFilter").AddCustomParameter("validUntil", unix));
```

**Comment by redox** [comment] 2016-10-10 20:24
@CBaptiste do you mind checking what happens?

**Comment by CBaptiste** [comment] 2016-10-20 09:05
Hey @redox, sorry for the delay, 
What do you mean by `it will not work` ?
I had the issue for a customer last week and it turned out that the way C# computes the unix timestamp is not supported by the engine (there is a comma in the timestamp) so there is an additional step to `Round`the unix timestamp.
What is the issue that you get ?

Thank you

**Comment by CBaptiste** [comment] 2016-10-20 09:12
ok @redox I found the thread on helpscout, I am on it !

**Comment by CBaptiste** [comment] 2016-10-20 09:28
I cannot reproduce the issue @redox, 
```
string date = (DateTime.UtcNow.AddHours(1) - new DateTime(1970, 1, 1, 0, 0, 0, 0)).TotalSeconds.ToString(CultureInfo.InvariantCulture);
var unix = Math.Round(Double.Parse(date, CultureInfo.InvariantCulture)).ToString();
var key = client.GenerateSecuredApiKey("KEY", new Query().SetFilters("type:issue").AddCustomParameter("validUntil", unix));
```
It works fine.
I am closing this and we ll have a quick chat about it !

**Closed by CBaptiste** 2016-10-20 09:28 UTC

**Comment by CBaptiste** [comment] 2016-10-20 12:30
I improved a little bit the doc regarding this
https://github.com/algolia/algoliasearch-client-readme-generator/commit/4ee81137f7275367b62a915c457508f8581adb32
