### ISSUE TITLE
RetryStrategy failed to connect to Algolia. Reason: Error while copying content to a stream.

### ISSUE THREAD

**Issue by treping** [algolia/algoliasearch-client-csharp#764] opened 2021-03-16 14:50 UTC
we did a integration of Algilia 6 month a ago, everthing was fine and we put the project on hold

try to re start the project this morning and we got this error on every step
RetryStrategy failed to connect to Algolia. Reason: Error while copying content to a stream.

  if (client != null) { return; }

        client = new SearchClient(Configs.AgoliaAPPID, Configs.AgoliaSearchAPIKEY);
        index = client.InitIndex(Configs.AgoliaIndex);
        IndexSettings settings = new IndexSettings() { AttributesForFaceting = new List<string> { "filterOnly(type)", "filterOnly(category)" } };

        index.SetSettings(settings);

**Comment by Ant-hem** [comment] 2021-03-16 21:41
Hello, thanks for reporting the issue. Which version of the sdk are you using?

**Comment by treping** [comment] 2021-03-17 12:49
I move from 6.6.0 to 6.9.1
6.6.0 : give me unable to connect to host

**Comment by Ant-hem** [comment] 2021-03-18 14:50
Can you run this minimal snippet and copy us the error, if any?

```csharp
using System;
using System.Net.Http;
using System.Text;

HttpClient client = new HttpClient();

client.DefaultRequestHeaders.Add("X-Algolia-Application-Id", "YOUR_APPLICATION_ID");
client.DefaultRequestHeaders.Add("X-Algolia-API-Key", "YOUR_API_KEY");

var content = await client.PostAsync("https://YOUR_APPLICATION_ID-dsn.algolia.net/1/indexes/YOUR_INDEX/query", new StringContent("{\"query\": \"\"}", Encoding.UTF8, "application/json"));
Console.WriteLine(content);
```

**Comment by treping** [comment] 2021-03-22 12:41
StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
--
  | {
  | Cache-Control: no-store
  | Connection: keep-alive
  | Date: Mon, 22 Mar 2021 12:36:02 GMT
  | Server: nginx
  | X-Alg-PT: 1
  | Accept-Encoding: deflate, gzip
  | Access-Control-Allow-Origin: *
  | Timing-Allow-Origin: *
  | X-Content-Type-Options: nosniff
  | Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  | Content-Length: 128
  | Content-Type: application/json; charset=UTF-8
  | Content-Disposition: inline; filename=a.txt
  | }

{"hits":[],"nbHits":0,"page":0,"nbPages":0,"hitsPerPage":20,"exhaustiveNbHits":true,"query":"","params":"","processingTimeMS":1}

**Comment by treping** [comment] 2021-03-22 17:19
insert work but it trigger this error

[AlgoliaUnreachableHostException: RetryStrategy failed to connect to Algolia. Reason: Error while copying content to a stream.]    Algolia.Search.Transport.<ExecuteRequestAsync>d__7`2.MoveNext() +335    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64    Algolia.Search.Clients.<BatchAsync>d__21`1.MoveNext() +334    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64    Algolia.Search.Clients.<SplitIntoBatchesAsync>d__20`1.MoveNext() +1062    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64    Algolia.Search.Clients.<SaveObjectsAsync>d__14`1.MoveNext() +595    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64    Algolia.Search.Clients.<SaveObjectAsync>d__12`1.MoveNext() +313    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64    Algolia.Search.Utils.AsyncHelper.RunSync(Func`1 func) +159    Algolia.Search.Clients.SearchIndex.SaveObject(T data, RequestOptions requestOptions, Boolean autoGenerateObjectId) +120
--

**Comment by treping** [comment] 2021-03-22 17:27
if a move to 
Install-Package Algolia.Search -Version 6.8.0

Unreachable hosts
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: Algolia.Search.Exceptions.AlgoliaUnreachableHostException: Unreachable hosts

Source Error:

**Comment by Ant-hem** [comment] 2021-03-22 18:09
Would you have the full stack-trace of the error?
Which version of the .NET Framework are you using? 
In what kind of application are you running the SDK? Console app? ASP.NET?

**Comment by treping** [comment] 2021-03-22 18:32
.NET 4.6
web project 

[AlgoliaUnreachableHostException: Unreachable hosts]    Algolia.Search.Transport.<ExecuteRequestAsync>d__6`2.MoveNext() +375    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64    Algolia.Search.Clients.<SetSettingsAsync>d__63.MoveNext() +382    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64    Algolia.Search.Utils.AsyncHelper.RunSync(Func`1 func) +160    Algolia.Search.Clients.SearchIndex.SetSettings(IndexSettings settings, RequestOptions requestOptions, Boolean forwardToReplicas) +93    AlgoliaService.Init() in c:\code\Yoyomolo\Projet\App_Code\Services\AlgoliaService.cs:39    AlgoliaService.UpdateAll() in c:\code\Yoyomolo\Projet\App_Code\Services\AlgoliaService.cs:227    <ProcessRequestAsync>d__0.MoveNext() in c:\code\Yoyomolo\Projet\App_Code\Services\AlgoliaHandler.cs:21    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64    System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar) +63    System.Web.HttpTaskAsyncHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +7    System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +576    System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +132    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +163
--

**Comment by Ant-hem** [comment] 2021-03-22 18:46
Could  you please try to set `System.Net.ServicePointManager.SecurityProtocol` to `SecurityProtocolType.Tls12`?

TLS 1.1 was deprecated by Algolia not so long ago and I wonder if that could be the cause.
https://www.algolia.com/doc/faq/security-privacy/is-my-data-encrypted-and-secured/

**Comment by treping** [comment] 2021-03-22 18:59
System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

it doesn't work
i log in algolia admin  everthing seem fine 
in Search API LOGS  i see POST 200 for every call
the SDK is throwing error for all the call

**Comment by TomKlotzPro** [comment] 2021-03-23 14:35
Hey @treping ! Jumping on this, Sorry to hear you are facing issue using our API client.

Could you ensure your are using TLS 1.2 ? 
Algolia's API in last few month change, and it doesn't accept TLS 1.1 which may be the origin of your issue. 

Here is a post that would help you ensure for us that you are using TLS 1.2 for .Net 4.6 : https://stackoverflow.com/questions/45382254/update-net-web-service-to-use-tls-1-2

Otherwise I'm not able to reproduce your issue locall.

Let us know how it goes, we would be really happy to help you.

**Comment by Ant-hem** [comment] 2021-04-16 10:13
Closing this issue since we didn't got update. Feel free to re-open if the issue is not solved.

**Closed by Ant-hem** 2021-04-16 10:13 UTC
